const texto = {
  vidaPessoal: {
    titulo: "Vida Pessoal",
    corpoTexto: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate voluptatum nemo error sed aspernatur eius excepturi animi nostrum repudiandae pariatur quo, aliquam eos velit praesentium atque nisi unde vero optio facere qui. Voluptate repellat blanditiis officiis nostrum quidem excepturi commodi omnis amet accusantium. Ipsam neque voluptatum earum! Magni facilis quis assumenda vel sint quod ad consequuntur. Reiciendis rerum ab consequatur, reprehenderit amet aut perspiciatis dignissimos accusamus beatae nam cumque enim nulla vel temporibus velit delectus, doloribus, adipisci harum mollitia a et maiores? Expedita vitae unde consequuntur eaque, ratione quidem quisquam quaerat eos porro sed incidunt, at voluptatem itaque animi tenetur.
Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate voluptatum nemo error sed aspernatur eius excepturi animi nostrum repudiandae pariatur quo, aliquam eos velit praesentium atque nisi unde vero optio facere qui. Voluptate repellat blanditiis officiis nostrum quidem excepturi commodi omnis amet accusantium. Ipsam neque voluptatum earum! Magni facilis quis assumenda vel sint quod ad consequuntur. Reiciendis rerum ab consequatur, reprehenderit amet aut perspiciatis dignissimos accusamus beatae nam cumque enim nulla vel temporibus velit delectus, doloribus, adipisci harum mollitia a et maiores? Expedita vitae unde consequuntur eaque, ratione quidem quisquam quaerat eos porro sed incidunt, at voluptatem itaque animi tenetur.
Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate voluptatum nemo error sed aspernatur eius excepturi animi nostrum repudiandae pariatur quo, aliquam eos velit praesentium atque nisi unde vero optio facere qui. Voluptate repellat blanditiis officiis nostrum quidem excepturi commodi omnis amet accusantium. Ipsam neque voluptatum earum! Magni facilis quis assumenda vel sint quod ad consequuntur. Reiciendis rerum ab consequatur, reprehenderit amet aut perspiciatis dignissimos accusamus beatae nam cumque enim nulla vel temporibus velit delectus, doloribus, adipisci harum mollitia a et maiores? Expedita vitae unde consequuntur eaque, ratione quidem quisquam quaerat eos porro sed incidunt, at voluptatem itaque animi tenetur.`
  },
}

export default texto;