/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/cardAluno/cardAluno`; params?: Router.UnknownInputParams; } | { pathname: `/../components/cardAluno/CardAluno`; params?: Router.UnknownInputParams; } | { pathname: `/../components/CardAluno/CardAluno`; params?: Router.UnknownInputParams; } | { pathname: `/editData`; params?: Router.UnknownInputParams; } | { pathname: `/../components/CardNota/CardNota`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/cardAluno/cardAluno`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/cardAluno/CardAluno`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/CardAluno/CardAluno`; params?: Router.UnknownOutputParams; } | { pathname: `/editData`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/CardNota/CardNota`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../components/cardAluno/cardAluno${`?${string}` | `#${string}` | ''}` | `/../components/cardAluno/CardAluno${`?${string}` | `#${string}` | ''}` | `/../components/CardAluno/CardAluno${`?${string}` | `#${string}` | ''}` | `/editData${`?${string}` | `#${string}` | ''}` | `/../components/CardNota/CardNota${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/cardAluno/cardAluno`; params?: Router.UnknownInputParams; } | { pathname: `/../components/cardAluno/CardAluno`; params?: Router.UnknownInputParams; } | { pathname: `/../components/CardAluno/CardAluno`; params?: Router.UnknownInputParams; } | { pathname: `/editData`; params?: Router.UnknownInputParams; } | { pathname: `/../components/CardNota/CardNota`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
